### PR TITLE
Update documentation for IPlugin.h

### LINKED ISSUE #9: Make decent doc

### PR DESCRIPTION
**Pull request by dcavalei**

### CODE REVIEW

**Comment by fncbarros** [comment]
Looking good. Can you add the subject too please?

**Comment by fncbarros** [comment]
Not a subject for this PR, but we should reach a conclusion on whether using an empty implementation is preferable to using "delete" to conform with the subject rule "Any class that declares at least one attribute must be written in canonical form".

**Comment by fncbarros** [comment]
How can I build for debug mode again? Can we add that in the Readme pls?

**Comment by dcavalei** [comment]
> Not a subject for this PR, but we should reach a conclusion on whether using an empty implementation is preferable to using "delete" to conform with the subject rule "Any class that declares at least one attribute must be written in canonical form".

IMO we should focus on developing, after we have the game as we wish we can adapt things to pass the shitty requirements.

> How can I build for debug mode again? Can we add that in the Readme pls? Same for running the program normally (args)

Done

**Review by fncbarros — APPROVED** [review]

**Comment by fncbarros** [comment]
> > Not a subject for this PR, but we should reach a conclusion on whether using an empty implementation is preferable to using "delete" to conform with the subject rule "Any class that declares at least one attribute must be written in canonical form".
> 
> IMO we should focus on developing, after we have the game as we wish we can adapt things to pass the shitty requirements.
> 
> > How can I build for debug mode again? Can we add that in the Readme pls? Same for running the program normally (args)
> 
> Done

Fair enough. LGTM

**Pull request merged**
